// scripts/test-google-workspace-tools.ts — Integration tests for real Google Workspace tools
// Tests Gmail, Drive, Docs, and Sheets tools against the authenticated Google account.

import { toolRegistry } from '../tools/registry';
import { registerGmailTools } from '../tools/google/gmail';
import { registerDriveTools } from '../tools/google/drive';
import { registerDocsTools } from '../tools/google/docs';
import { registerSheetsTools } from '../tools/google/sheets';
import { getGoogleAuthStatus } from '../lib/google-auth';

interface TestResult {
  suite: string;
  name: string;
  passed: boolean;
  error?: string;
  details?: unknown;
}

const results: TestResult[] = [];

function record(suite: string, name: string, passed: boolean, error?: string, details?: unknown) {
  results.push({ suite, name, passed, error, details });
  const icon = passed ? '✅' : '❌';
  console.log(`  ${icon} [${suite}] ${name}${error ? ` -> ${error}` : ''}`);
}

async function runWorkspaceTests() {
  console.log('🧪 Starting Real Google Workspace Tools Integration Test Suite...\n');

  // Register all real tools
  registerGmailTools();
  registerDriveTools();
  registerDocsTools();
  registerSheetsTools();

  // 1. Check Auth Status
  console.log('1. Checking Google OAuth Connection...');
  const status = await getGoogleAuthStatus();
  if (!status.isConnected || !status.email) {
    console.error('❌ Google account is not connected! Run OAuth login first.');
    process.exit(1);
  }
  console.log(`   Connected user: ${status.email} (Store: ${status.storeType})\n`);

  // 2. Google Drive Tests
  console.log('2. Testing Google Drive Tools (drive.search, drive.list, drive.createFolder)...');
  const driveSearchRes = await toolRegistry.execute('drive.search', { query: '', pageSize: 5 });
  record('Drive', 'drive.search (recent files)', driveSearchRes.success, driveSearchRes.error, driveSearchRes.result);

  const driveListRes = await toolRegistry.execute('drive.list', { pageSize: 5 });
  record('Drive', 'drive.list', driveListRes.success, driveListRes.error);

  let testFolderId: string | undefined;
  const folderRes = await toolRegistry.execute('drive.createFolder', { name: `Murmur Test Folder (${Date.now()})` });
  record('Drive', 'drive.createFolder', folderRes.success, folderRes.error, folderRes.result);
  if (folderRes.success && folderRes.result) {
    testFolderId = (folderRes.result as any).folderId;
  }

  // 3. Google Docs Tests
  console.log('\n3. Testing Google Docs Tools (docs.create, docs.read, docs.update)...');
  const docCreateRes = await toolRegistry.execute('docs.create', {
    title: `Murmur Real Integration Doc (${new Date().toLocaleTimeString()})`,
    content: 'This is an authentic document generated by Murmur AI paired with the official Google Docs API.',
  });
  record('Docs', 'docs.create (authentic document)', docCreateRes.success, docCreateRes.error, docCreateRes.result);

  let createdDocId: string | undefined;
  let createdDocUrl: string | undefined;
  if (docCreateRes.success && docCreateRes.result) {
    createdDocId = (docCreateRes.result as any).documentId;
    createdDocUrl = (docCreateRes.result as any).url;
    console.log(`   📄 Created Doc URL: ${createdDocUrl}`);

    // Test docs.read
    const docReadRes = await toolRegistry.execute('docs.read', { documentId: createdDocId });
    record('Docs', 'docs.read (verify content)', docReadRes.success, docReadRes.error);

    // Test docs.update
    const docUpdateRes = await toolRegistry.execute('docs.update', {
      documentId: createdDocId,
      content: 'Added Section: Verified text insertion at ' + new Date().toISOString(),
    });
    record('Docs', 'docs.update (append text)', docUpdateRes.success, docUpdateRes.error);
  }

  // 4. Google Sheets Tests
  console.log('\n4. Testing Google Sheets Tools (sheets.create, sheets.read, sheets.update, sheets.append)...');
  const sheetCreateRes = await toolRegistry.execute('sheets.create', {
    title: `Murmur Test Sheet (${new Date().toLocaleTimeString()})`,
    headers: 'ID, Task, Status, Timestamp',
    data: JSON.stringify([
      ['TSK-001', 'Verify Google Docs API', 'Done', new Date().toISOString()],
      ['TSK-002', 'Verify Google Sheets API', 'In Progress', new Date().toISOString()],
    ]),
  });
  record('Sheets', 'sheets.create (authentic spreadsheet)', sheetCreateRes.success, sheetCreateRes.error, sheetCreateRes.result);

  let createdSheetId: string | undefined;
  let createdSheetUrl: string | undefined;
  if (sheetCreateRes.success && sheetCreateRes.result) {
    createdSheetId = (sheetCreateRes.result as any).spreadsheetId;
    createdSheetUrl = (sheetCreateRes.result as any).url;
    console.log(`   📊 Created Sheet URL: ${createdSheetUrl}`);

    // Test sheets.read
    const sheetReadRes = await toolRegistry.execute('sheets.read', {
      spreadsheetId: createdSheetId,
      range: 'Sheet1!A1:D3',
    });
    record('Sheets', 'sheets.read', sheetReadRes.success, sheetReadRes.error);

    // Test sheets.append
    const sheetAppendRes = await toolRegistry.execute('sheets.append', {
      spreadsheetId: createdSheetId,
      range: 'Sheet1',
      data: JSON.stringify([['TSK-003', 'Verify Gmail API', 'Testing', new Date().toISOString()]]),
    });
    record('Sheets', 'sheets.append', sheetAppendRes.success, sheetAppendRes.error);
  }

  // 5. Gmail Tests
  console.log('\n5. Testing Gmail Tools (gmail.search, gmail.draft, gmail.send)...');
  const gmailSearchRes = await toolRegistry.execute('gmail.search', { query: 'label:inbox', maxResults: 3 });
  record('Gmail', 'gmail.search', gmailSearchRes.success, gmailSearchRes.error, gmailSearchRes.result);

  const gmailDraftRes = await toolRegistry.execute('gmail.draft', {
    to: status.email,
    subject: `Murmur Draft Test (${Date.now()})`,
    body: 'This is a draft message generated by Murmur Agent.',
  });
  record('Gmail', 'gmail.draft', gmailDraftRes.success, gmailDraftRes.error);

  const gmailSendRes = await toolRegistry.execute('gmail.send', {
    to: status.email,
    subject: `Murmur Self-Test Email (${Date.now()})`,
    body: 'Automated self-test confirming Murmur Gmail sending capability.\n\nAll systems operational.',
  });
  record('Gmail', 'gmail.send (controlled self-test)', gmailSendRes.success, gmailSendRes.error, gmailSendRes.result);

  // Summary
  console.log('\n==========================================');
  console.log('🏁 GOOGLE WORKSPACE TEST SUMMARY:');
  const passedCount = results.filter((r) => r.passed).length;
  console.log(`Passed: ${passedCount} / ${results.length}`);

  if (createdDocUrl) console.log(`\nGoogle Doc created: ${createdDocUrl}`);
  if (createdSheetUrl) console.log(`Google Sheet created: ${createdSheetUrl}`);
}

runWorkspaceTests().catch((err) => {
  console.error('Fatal test error:', err);
  process.exit(1);
});
